---
# This playbook contain common plays that will be run on all nodes

- name: remove invalid unattended upgrades
  file:
    path: /etc/apt/apt.conf.d/50unattended-upgrades.ucf-dist
    state: absent

- name: update and upgrade all packages
  apt:
    upgrade: dist
